# Generated by Django 5.1.5 on 2025-08-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='initiated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
    ]
